prompts = [
    "The old house on the hill had always been a place of mystery.",
    "One night, the sound of footsteps echoed through the empty halls.",
    "In the attic, an ancient book lay covered in dust.",
    "The pages of the book revealed a forgotten family secret.",
    "Sarah couldn't believe what she was reading.",
    "Her great-grandmother had been accused of witchcraft.",
    "Desperate to learn more, Sarah decided to visit the local library.",
    "There, she found an old newspaper article about a hidden treasure.",
    "The treasure was said to be buried somewhere on her family's property.",
    "Armed with a shovel and a map, Sarah began her search.",
    "Hours passed, and she dug tirelessly under the moonlight.",
    "Just as she was about to give up, her shovel hit something hard.",
    "She unearthed a small, rusty chest.",
    "With trembling hands, she opened the chest to reveal a collection of old letters.",
    "The letters were written by her great-grandmother, detailing her escape from persecution.",
    "One letter mentioned a secret passage in the house.",
    "Sarah rushed back to the house to find the hidden passage.",
    "Behind a false wall in the basement, she discovered a narrow staircase.",
    "The staircase led to an underground room filled with artifacts.",
    "Among the artifacts was a locket with a picture of her great-grandmother.",
    "Inside the locket was a tiny key.",
    "The key fit a small, ornate box found in the corner of the room.",
    "The box contained a detailed map to the real treasure.",
    "The map led Sarah to an old oak tree in the backyard.",
    "Beneath the tree, she found a chest filled with gold coins and jewels."
]